# Generated by Django 3.2.8 on 2024-09-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0147_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='ZbR0gZXdNO', max_length=30),
        ),
    ]
