# Generated by Django 3.2.8 on 2024-10-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0149_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='808EFf1gIX', max_length=30),
        ),
    ]
