# Generated by Django 3.2.8 on 2024-10-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0150_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='H3hfmVKTD8', max_length=30),
        ),
    ]
