# Generated by Django 3.2.8 on 2024-10-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0151_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='3TEdXa5mvg', max_length=30),
        ),
    ]
