# Generated by Django 3.2.8 on 2024-10-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0152_alter_branch_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='certificate_days_left',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='eDYmo4jIaB', max_length=30),
        ),
    ]
