# Generated by Django 3.2.8 on 2024-10-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_unit_measures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit_measures',
            old_name='_id',
            new_name='id_unit',
        ),
    ]
