# Generated by Django 3.2.8 on 2024-10-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0146_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='aqyL0WqpXJrm6lgi0eBC', max_length=20, unique=True),
        ),
    ]
