# Generated by Django 3.2.8 on 2024-10-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0148_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='b8TQKYjYziunJoiDuded', max_length=20, unique=True),
        ),
    ]
