# Generated by Django 3.2.8 on 2024-10-18 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0148_alter_employee_psswd'),
        ('invoice', '0033_auto_20241017_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Closings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totals_subtotal', models.FloatField(blank=True, default=0, null=True)),
                ('totals_taxes', models.FloatField(blank=True, default=0, null=True)),
                ('totals_ipo', models.FloatField(blank=True, default=0, null=True)),
                ('totals_discount', models.FloatField(blank=True, default=0, null=True)),
                ('totals', models.FloatField(blank=True, default=0, null=True)),
                ('time_start', models.TimeField(auto_now_add=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('base', models.FloatField(blank=True, null=True)),
                ('finalized', models.BooleanField(blank=True, default=False, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('cash_closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='invoice.cash_closings')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='cash_closing_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.cash_closings'),
        ),
    ]
